version: "3.9"
services:
  server:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - "db"
    restart: "on-failure"
    networks:
      - "internal"
    environment:
      PORT: "8080"


networks:
  internal:
    driver: "bridge"