// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Weapon struct {
	Name    string `json:"name"`
	Type    string `json:"type"`
	Phy     int    `json:"phy"`
	Mag     int    `json:"mag"`
	Fir     int    `json:"fir"`
	Lit     int    `json:"lit"`
	Hol     int    `json:"hol"`
	Cri     int    `json:"cri"`
	Sta     int    `json:"sta"`
	Str     string `json:"str"`
	Dex     string `json:"dex"`
	Int     string `json:"int"`
	Fai     string `json:"fai"`
	Arc     string `json:"arc"`
	Any     string `json:"any"`
	Phyb    int    `json:"phyb"`
	Magb    int    `json:"magb"`
	Firb    int    `json:"firb"`
	Litb    int    `json:"litb"`
	Holb    int    `json:"holb"`
	Bst     string `json:"bst"`
	Rst     string `json:"Rst"`
	Wgt     string `json:"wgt"`
	Upgrade string `json:"upgrade"`
	ID      string `json:"id"`
	Custom  bool   `json:"custom"`
}
